/*
 * Conekta API
 *
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Conekta.net.Client.OpenAPIDateConverter;

namespace Conekta.net.Model
{
    /// <summary>
    /// Chargeback object
    /// </summary>
    [DataContract(Name = "chargeback_response")]
    public partial class ChargebackResponse : IValidatableObject
    {
        /// <summary>
        /// Defines Status
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Won for value: won
            /// </summary>
            [EnumMember(Value = "won")]
            Won = 1,

            /// <summary>
            /// Enum Lost for value: lost
            /// </summary>
            [EnumMember(Value = "lost")]
            Lost = 2,

            /// <summary>
            /// Enum ActionRequired for value: action_required
            /// </summary>
            [EnumMember(Value = "action_required")]
            ActionRequired = 3,

            /// <summary>
            /// Enum PendingReview for value: pending_review
            /// </summary>
            [EnumMember(Value = "pending_review")]
            PendingReview = 4,

            /// <summary>
            /// Enum UnderReview for value: under_review
            /// </summary>
            [EnumMember(Value = "under_review")]
            UnderReview = 5,

            /// <summary>
            /// Enum Covered for value: covered
            /// </summary>
            [EnumMember(Value = "covered")]
            Covered = 6,

            /// <summary>
            /// Enum Rt for value: rt
            /// </summary>
            [EnumMember(Value = "rt")]
            Rt = 7,

            /// <summary>
            /// Enum RtSent for value: rt_sent
            /// </summary>
            [EnumMember(Value = "rt_sent")]
            RtSent = 8,

            /// <summary>
            /// Enum Represented for value: represented
            /// </summary>
            [EnumMember(Value = "represented")]
            Represented = 9
        }


        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        /*
        <example>lost</example>
        */
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public StatusEnum? Status { get; set; }
        /// <summary>
        /// Defines Reason
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ReasonEnum
        {
            /// <summary>
            /// Enum Unrecognized for value: unrecognized
            /// </summary>
            [EnumMember(Value = "unrecognized")]
            Unrecognized = 1,

            /// <summary>
            /// Enum Unauthorized for value: unauthorized
            /// </summary>
            [EnumMember(Value = "unauthorized")]
            Unauthorized = 2,

            /// <summary>
            /// Enum UnauthorizedByClient for value: unauthorized_by_client
            /// </summary>
            [EnumMember(Value = "unauthorized_by_client")]
            UnauthorizedByClient = 3,

            /// <summary>
            /// Enum UnrecognizedLikeFraud for value: unrecognized_like_fraud
            /// </summary>
            [EnumMember(Value = "unrecognized_like_fraud")]
            UnrecognizedLikeFraud = 4,

            /// <summary>
            /// Enum InsufficientEvidence for value: insufficient_evidence
            /// </summary>
            [EnumMember(Value = "insufficient_evidence")]
            InsufficientEvidence = 5,

            /// <summary>
            /// Enum IllegibleEvidence for value: illegible_evidence
            /// </summary>
            [EnumMember(Value = "illegible_evidence")]
            IllegibleEvidence = 6,

            /// <summary>
            /// Enum General for value: general
            /// </summary>
            [EnumMember(Value = "general")]
            General = 7,

            /// <summary>
            /// Enum LateEvidence for value: late_evidence
            /// </summary>
            [EnumMember(Value = "late_evidence")]
            LateEvidence = 8,

            /// <summary>
            /// Enum IncorrectExchange for value: incorrect_exchange
            /// </summary>
            [EnumMember(Value = "incorrect_exchange")]
            IncorrectExchange = 9,

            /// <summary>
            /// Enum FraudulentBusiness for value: fraudulent_business
            /// </summary>
            [EnumMember(Value = "fraudulent_business")]
            FraudulentBusiness = 10,

            /// <summary>
            /// Enum Billing for value: billing
            /// </summary>
            [EnumMember(Value = "billing")]
            Billing = 11,

            /// <summary>
            /// Enum TwiceTransaction for value: twice_transaction
            /// </summary>
            [EnumMember(Value = "twice_transaction")]
            TwiceTransaction = 12,

            /// <summary>
            /// Enum TransactionNotRefunded for value: transaction_not_refunded
            /// </summary>
            [EnumMember(Value = "transaction_not_refunded")]
            TransactionNotRefunded = 13,

            /// <summary>
            /// Enum BankDocRequest for value: bank_doc_request
            /// </summary>
            [EnumMember(Value = "bank_doc_request")]
            BankDocRequest = 14,

            /// <summary>
            /// Enum UnrecognizedPurchase for value: unrecognized_purchase
            /// </summary>
            [EnumMember(Value = "unrecognized_purchase")]
            UnrecognizedPurchase = 15,

            /// <summary>
            /// Enum SubscriptionCanceled for value: subscription_canceled
            /// </summary>
            [EnumMember(Value = "subscription_canceled")]
            SubscriptionCanceled = 16,

            /// <summary>
            /// Enum CopyOfPurchase for value: copy_of_purchase
            /// </summary>
            [EnumMember(Value = "copy_of_purchase")]
            CopyOfPurchase = 17,

            /// <summary>
            /// Enum DifferentsAmounts for value: differents_amounts
            /// </summary>
            [EnumMember(Value = "differents_amounts")]
            DifferentsAmounts = 18,

            /// <summary>
            /// Enum SubscriptionNotRequested for value: subscription_not_requested
            /// </summary>
            [EnumMember(Value = "subscription_not_requested")]
            SubscriptionNotRequested = 19,

            /// <summary>
            /// Enum DamagedProducts for value: damaged_products
            /// </summary>
            [EnumMember(Value = "damaged_products")]
            DamagedProducts = 20,

            /// <summary>
            /// Enum ShowDocuments for value: show_documents
            /// </summary>
            [EnumMember(Value = "show_documents")]
            ShowDocuments = 21,

            /// <summary>
            /// Enum Duplicate for value: duplicate
            /// </summary>
            [EnumMember(Value = "duplicate")]
            Duplicate = 22,

            /// <summary>
            /// Enum Fraudulent for value: fraudulent
            /// </summary>
            [EnumMember(Value = "fraudulent")]
            Fraudulent = 23,

            /// <summary>
            /// Enum ServiceCanceled for value: service_canceled
            /// </summary>
            [EnumMember(Value = "service_canceled")]
            ServiceCanceled = 24,

            /// <summary>
            /// Enum ProductUnacceptable for value: product_unacceptable
            /// </summary>
            [EnumMember(Value = "product_unacceptable")]
            ProductUnacceptable = 25,

            /// <summary>
            /// Enum ProductNotReceived for value: product_not_received
            /// </summary>
            [EnumMember(Value = "product_not_received")]
            ProductNotReceived = 26,

            /// <summary>
            /// Enum IncorrectAmount for value: incorrect_amount
            /// </summary>
            [EnumMember(Value = "incorrect_amount")]
            IncorrectAmount = 27,

            /// <summary>
            /// Enum ChipLiabiliatyShift for value: chip_liabiliaty_shift
            /// </summary>
            [EnumMember(Value = "chip_liabiliaty_shift")]
            ChipLiabiliatyShift = 28,

            /// <summary>
            /// Enum CreditNotProcessed for value: credit_not_processed
            /// </summary>
            [EnumMember(Value = "credit_not_processed")]
            CreditNotProcessed = 29
        }


        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        /*
        <example>unrecognized</example>
        */
        [DataMember(Name = "reason", EmitDefaultValue = false)]
        public ReasonEnum? Reason { get; set; }
        /// <summary>
        /// Defines FollowupStatus
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum FollowupStatusEnum
        {
            /// <summary>
            /// Enum Uncontacted for value: customer_uncontacted
            /// </summary>
            [EnumMember(Value = "customer_uncontacted")]
            Uncontacted = 1,

            /// <summary>
            /// Enum Contacted for value: customer_contacted
            /// </summary>
            [EnumMember(Value = "customer_contacted")]
            Contacted = 2,

            /// <summary>
            /// Enum Unreachable for value: customer_unreachable
            /// </summary>
            [EnumMember(Value = "customer_unreachable")]
            Unreachable = 3
        }


        /// <summary>
        /// Gets or Sets FollowupStatus
        /// </summary>
        [DataMember(Name = "followup_status", EmitDefaultValue = false)]
        public FollowupStatusEnum? FollowupStatus { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ChargebackResponse" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="status">status.</param>
        /// <param name="reason">reason.</param>
        /// <param name="note">note.</param>
        /// <param name="followupStatus">followupStatus.</param>
        /// <param name="responseFromClient">responseFromClient.</param>
        /// <param name="files">files.</param>
        /// <param name="varObject">varObject.</param>
        /// <param name="chargeId">chargeId.</param>
        /// <param name="createdAt">createdAt.</param>
        /// <param name="evidenceDueBy">evidenceDueBy.</param>
        public ChargebackResponse(string id = default(string), StatusEnum? status = default(StatusEnum?), ReasonEnum? reason = default(ReasonEnum?), string note = default(string), FollowupStatusEnum? followupStatus = default(FollowupStatusEnum?), string responseFromClient = default(string), List<ChargebackFileResponse> files = default(List<ChargebackFileResponse>), string varObject = default(string), string chargeId = default(string), long createdAt = default(long), long evidenceDueBy = default(long))
        {
            this.Id = id;
            this.Status = status;
            this.Reason = reason;
            this.Note = note;
            this.FollowupStatus = followupStatus;
            this.ResponseFromClient = responseFromClient;
            this.Files = files;
            this.Object = varObject;
            this.ChargeId = chargeId;
            this.CreatedAt = createdAt;
            this.EvidenceDueBy = evidenceDueBy;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        /*
        <example>chbk_2zPxWFUnGNLySoumn</example>
        */
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Note
        /// </summary>
        [DataMember(Name = "note", EmitDefaultValue = false)]
        public string Note { get; set; }

        /// <summary>
        /// Gets or Sets ResponseFromClient
        /// </summary>
        [DataMember(Name = "response_from_client", EmitDefaultValue = false)]
        public string ResponseFromClient { get; set; }

        /// <summary>
        /// Gets or Sets Files
        /// </summary>
        [DataMember(Name = "files", EmitDefaultValue = false)]
        public List<ChargebackFileResponse> Files { get; set; }

        /// <summary>
        /// Gets or Sets Object
        /// </summary>
        /*
        <example>chargeback</example>
        */
        [DataMember(Name = "object", EmitDefaultValue = false)]
        public string Object { get; set; }

        /// <summary>
        /// Gets or Sets ChargeId
        /// </summary>
        /*
        <example>6966a06c044243000156c24d</example>
        */
        [DataMember(Name = "charge_id", EmitDefaultValue = false)]
        public string ChargeId { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        /*
        <example>1768846800</example>
        */
        [DataMember(Name = "created_at", EmitDefaultValue = false)]
        public long CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets EvidenceDueBy
        /// </summary>
        /*
        <example>1769126399</example>
        */
        [DataMember(Name = "evidence_due_by", EmitDefaultValue = false)]
        public long EvidenceDueBy { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ChargebackResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  Note: ").Append(Note).Append("\n");
            sb.Append("  FollowupStatus: ").Append(FollowupStatus).Append("\n");
            sb.Append("  ResponseFromClient: ").Append(ResponseFromClient).Append("\n");
            sb.Append("  Files: ").Append(Files).Append("\n");
            sb.Append("  Object: ").Append(Object).Append("\n");
            sb.Append("  ChargeId: ").Append(ChargeId).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  EvidenceDueBy: ").Append(EvidenceDueBy).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
