/*
 * Conekta API
 *
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.3.0
 * Contact: engineering@conekta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Conekta.net.Client.OpenAPIDateConverter;

namespace Conekta.net.Model
{
    /// <summary>
    /// SubscriptionDetailsCard
    /// </summary>
    [DataContract(Name = "subscription_details_card")]
    public partial class SubscriptionDetailsCard : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SubscriptionDetailsCard" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="createdAt">createdAt.</param>
        /// <param name="active">active.</param>
        /// <param name="varObject">varObject.</param>
        /// <param name="expMonth">expMonth.</param>
        /// <param name="expYear">expYear.</param>
        /// <param name="brand">brand.</param>
        /// <param name="last4">last4.</param>
        /// <param name="name">name.</param>
        /// <param name="paymentSourceStatus">paymentSourceStatus.</param>
        /// <param name="customerId">customerId.</param>
        /// <param name="customerCustomReference">customerCustomReference.</param>
        public SubscriptionDetailsCard(string id = default(string), long createdAt = default(long), bool active = default(bool), string varObject = default(string), string expMonth = default(string), string expYear = default(string), string brand = default(string), string last4 = default(string), string name = default(string), string paymentSourceStatus = default(string), string customerId = default(string), string customerCustomReference = default(string))
        {
            this.Id = id;
            this.CreatedAt = createdAt;
            this.Active = active;
            this.Object = varObject;
            this.ExpMonth = expMonth;
            this.ExpYear = expYear;
            this.Brand = brand;
            this.Last4 = last4;
            this.Name = name;
            this.PaymentSourceStatus = paymentSourceStatus;
            this.CustomerId = customerId;
            this.CustomerCustomReference = customerCustomReference;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        /*
        <example>src_2yw5zPrVahTy7xy7P</example>
        */
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        /*
        <example>1761745218</example>
        */
        [DataMember(Name = "created_at", EmitDefaultValue = false)]
        public long CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets Active
        /// </summary>
        /*
        <example>true</example>
        */
        [DataMember(Name = "active", EmitDefaultValue = true)]
        public bool Active { get; set; }

        /// <summary>
        /// Gets or Sets Object
        /// </summary>
        /*
        <example>card</example>
        */
        [DataMember(Name = "object", EmitDefaultValue = false)]
        public string Object { get; set; }

        /// <summary>
        /// Gets or Sets ExpMonth
        /// </summary>
        /*
        <example>05</example>
        */
        [DataMember(Name = "exp_month", EmitDefaultValue = false)]
        public string ExpMonth { get; set; }

        /// <summary>
        /// Gets or Sets ExpYear
        /// </summary>
        /*
        <example>26</example>
        */
        [DataMember(Name = "exp_year", EmitDefaultValue = false)]
        public string ExpYear { get; set; }

        /// <summary>
        /// Gets or Sets Brand
        /// </summary>
        /*
        <example>mastercard</example>
        */
        [DataMember(Name = "brand", EmitDefaultValue = false)]
        public string Brand { get; set; }

        /// <summary>
        /// Gets or Sets Last4
        /// </summary>
        /*
        <example>1005</example>
        */
        [DataMember(Name = "last4", EmitDefaultValue = false)]
        public string Last4 { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        /*
        <example>test</example>
        */
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets PaymentSourceStatus
        /// </summary>
        /*
        <example>active</example>
        */
        [DataMember(Name = "payment_source_status", EmitDefaultValue = false)]
        public string PaymentSourceStatus { get; set; }

        /// <summary>
        /// Gets or Sets CustomerId
        /// </summary>
        /*
        <example>cus_2yDzKtEAD3khH8Sga</example>
        */
        [DataMember(Name = "customer_id", EmitDefaultValue = false)]
        public string CustomerId { get; set; }

        /// <summary>
        /// Gets or Sets CustomerCustomReference
        /// </summary>
        [DataMember(Name = "customer_custom_reference", EmitDefaultValue = false)]
        public string CustomerCustomReference { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SubscriptionDetailsCard {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Active: ").Append(Active).Append("\n");
            sb.Append("  Object: ").Append(Object).Append("\n");
            sb.Append("  ExpMonth: ").Append(ExpMonth).Append("\n");
            sb.Append("  ExpYear: ").Append(ExpYear).Append("\n");
            sb.Append("  Brand: ").Append(Brand).Append("\n");
            sb.Append("  Last4: ").Append(Last4).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  PaymentSourceStatus: ").Append(PaymentSourceStatus).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  CustomerCustomReference: ").Append(CustomerCustomReference).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
