/*
 * Conekta API
 *
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: engineering@conekta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Conekta.net.Client.OpenAPIDateConverter;

namespace Conekta.net.Model
{
    /// <summary>
    /// TokenResponseCheckout
    /// </summary>
    [DataContract(Name = "token_response_checkout")]
    public partial class TokenResponseCheckout : IEquatable<TokenResponseCheckout>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TokenResponseCheckout" /> class.
        /// </summary>
        /// <param name="allowedPaymentMethods">allowedPaymentMethods.</param>
        /// <param name="canNotExpire">Indicates if the checkout can not expire..</param>
        /// <param name="emailsSent">emailsSent.</param>
        /// <param name="excludeCardNetworks">excludeCardNetworks.</param>
        /// <param name="expiresAt">Date and time when the checkout expires..</param>
        /// <param name="failureUrl">URL to redirect the customer to if the payment process fails..</param>
        /// <param name="force3dsFlow">Indicates if the checkout forces the 3DS flow..</param>
        /// <param name="id">id.</param>
        /// <param name="livemode">livemode.</param>
        /// <param name="metadata">metadata.</param>
        /// <param name="monthlyInstallmentsEnabled">Indicates if the checkout allows monthly installments..</param>
        /// <param name="monthlyInstallmentsOptions">List of monthly installments options..</param>
        /// <param name="name">name.</param>
        /// <param name="needsShippingContact">needsShippingContact.</param>
        /// <param name="varObject">Indicates the type of object, in this case checkout..</param>
        /// <param name="onDemandEnabled">Indicates if the checkout allows on demand payments..</param>
        /// <param name="paidPaymentsCount">Number of payments that have been paid..</param>
        /// <param name="recurrent">Indicates if the checkout is recurrent..</param>
        /// <param name="smsSent">smsSent.</param>
        /// <param name="startsAt">Date and time when the checkout starts..</param>
        /// <param name="status">Status of the checkout..</param>
        /// <param name="successUrl">URL to redirect the customer to after the payment process is completed..</param>
        /// <param name="type">Type of checkout..</param>
        public TokenResponseCheckout(List<string> allowedPaymentMethods = default(List<string>), bool canNotExpire = default(bool), int emailsSent = default(int), List<string> excludeCardNetworks = default(List<string>), long expiresAt = default(long), string failureUrl = default(string), bool force3dsFlow = default(bool), string id = default(string), bool livemode = default(bool), Dictionary<string, Object> metadata = default(Dictionary<string, Object>), bool monthlyInstallmentsEnabled = default(bool), List<int> monthlyInstallmentsOptions = default(List<int>), string name = default(string), bool needsShippingContact = default(bool), string varObject = default(string), bool onDemandEnabled = default(bool), int paidPaymentsCount = default(int), bool recurrent = default(bool), int smsSent = default(int), long startsAt = default(long), string status = default(string), string successUrl = default(string), string type = default(string))
        {
            this.AllowedPaymentMethods = allowedPaymentMethods;
            this.CanNotExpire = canNotExpire;
            this.EmailsSent = emailsSent;
            this.ExcludeCardNetworks = excludeCardNetworks;
            this.ExpiresAt = expiresAt;
            this.FailureUrl = failureUrl;
            this.Force3dsFlow = force3dsFlow;
            this.Id = id;
            this.Livemode = livemode;
            this.Metadata = metadata;
            this.MonthlyInstallmentsEnabled = monthlyInstallmentsEnabled;
            this.MonthlyInstallmentsOptions = monthlyInstallmentsOptions;
            this.Name = name;
            this.NeedsShippingContact = needsShippingContact;
            this.VarObject = varObject;
            this.OnDemandEnabled = onDemandEnabled;
            this.PaidPaymentsCount = paidPaymentsCount;
            this.Recurrent = recurrent;
            this.SmsSent = smsSent;
            this.StartsAt = startsAt;
            this.Status = status;
            this.SuccessUrl = successUrl;
            this.Type = type;
        }

        /// <summary>
        /// Gets or Sets AllowedPaymentMethods
        /// </summary>
        [DataMember(Name = "allowed_payment_methods", EmitDefaultValue = false)]
        public List<string> AllowedPaymentMethods { get; set; }

        /// <summary>
        /// Indicates if the checkout can not expire.
        /// </summary>
        /// <value>Indicates if the checkout can not expire.</value>
        /// <example>false</example>
        [DataMember(Name = "can_not_expire", EmitDefaultValue = true)]
        public bool CanNotExpire { get; set; }

        /// <summary>
        /// Gets or Sets EmailsSent
        /// </summary>
        /// <example>0</example>
        [DataMember(Name = "emails_sent", EmitDefaultValue = false)]
        public int EmailsSent { get; set; }

        /// <summary>
        /// Gets or Sets ExcludeCardNetworks
        /// </summary>
        [DataMember(Name = "exclude_card_networks", EmitDefaultValue = false)]
        public List<string> ExcludeCardNetworks { get; set; }

        /// <summary>
        /// Date and time when the checkout expires.
        /// </summary>
        /// <value>Date and time when the checkout expires.</value>
        /// <example>1675715413</example>
        [DataMember(Name = "expires_at", EmitDefaultValue = false)]
        public long ExpiresAt { get; set; }

        /// <summary>
        /// URL to redirect the customer to if the payment process fails.
        /// </summary>
        /// <value>URL to redirect the customer to if the payment process fails.</value>
        /// <example>https://example.com/failure</example>
        [DataMember(Name = "failure_url", EmitDefaultValue = false)]
        public string FailureUrl { get; set; }

        /// <summary>
        /// Indicates if the checkout forces the 3DS flow.
        /// </summary>
        /// <value>Indicates if the checkout forces the 3DS flow.</value>
        /// <example>false</example>
        [DataMember(Name = "force_3ds_flow", EmitDefaultValue = true)]
        public bool Force3dsFlow { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        /// <example>524f9d2f-8c2e-4e64-a33d-6006711a91bd</example>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Livemode
        /// </summary>
        /// <example>true</example>
        [DataMember(Name = "livemode", EmitDefaultValue = true)]
        public bool Livemode { get; set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        /// <example>{&quot;key&quot;:&quot;value&quot;}</example>
        [DataMember(Name = "metadata", EmitDefaultValue = false)]
        public Dictionary<string, Object> Metadata { get; set; }

        /// <summary>
        /// Indicates if the checkout allows monthly installments.
        /// </summary>
        /// <value>Indicates if the checkout allows monthly installments.</value>
        /// <example>false</example>
        [DataMember(Name = "monthly_installments_enabled", EmitDefaultValue = true)]
        public bool MonthlyInstallmentsEnabled { get; set; }

        /// <summary>
        /// List of monthly installments options.
        /// </summary>
        /// <value>List of monthly installments options.</value>
        [DataMember(Name = "monthly_installments_options", EmitDefaultValue = false)]
        public List<int> MonthlyInstallmentsOptions { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        /// <example>tok-2toNoPZpJgRU4PvgZ</example>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets NeedsShippingContact
        /// </summary>
        /// <example>false</example>
        [DataMember(Name = "needs_shipping_contact", EmitDefaultValue = true)]
        public bool NeedsShippingContact { get; set; }

        /// <summary>
        /// Indicates the type of object, in this case checkout.
        /// </summary>
        /// <value>Indicates the type of object, in this case checkout.</value>
        /// <example>checkout</example>
        [DataMember(Name = "object", EmitDefaultValue = false)]
        public string VarObject { get; set; }

        /// <summary>
        /// Indicates if the checkout allows on demand payments.
        /// </summary>
        /// <value>Indicates if the checkout allows on demand payments.</value>
        /// <example>false</example>
        [DataMember(Name = "on_demand_enabled", EmitDefaultValue = true)]
        public bool OnDemandEnabled { get; set; }

        /// <summary>
        /// Number of payments that have been paid.
        /// </summary>
        /// <value>Number of payments that have been paid.</value>
        /// <example>0</example>
        [DataMember(Name = "paid_payments_count", EmitDefaultValue = false)]
        public int PaidPaymentsCount { get; set; }

        /// <summary>
        /// Indicates if the checkout is recurrent.
        /// </summary>
        /// <value>Indicates if the checkout is recurrent.</value>
        /// <example>false</example>
        [DataMember(Name = "recurrent", EmitDefaultValue = true)]
        public bool Recurrent { get; set; }

        /// <summary>
        /// Gets or Sets SmsSent
        /// </summary>
        /// <example>0</example>
        [DataMember(Name = "sms_sent", EmitDefaultValue = false)]
        public int SmsSent { get; set; }

        /// <summary>
        /// Date and time when the checkout starts.
        /// </summary>
        /// <value>Date and time when the checkout starts.</value>
        /// <example>1675715413</example>
        [DataMember(Name = "starts_at", EmitDefaultValue = false)]
        public long StartsAt { get; set; }

        /// <summary>
        /// Status of the checkout.
        /// </summary>
        /// <value>Status of the checkout.</value>
        /// <example>Issued</example>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public string Status { get; set; }

        /// <summary>
        /// URL to redirect the customer to after the payment process is completed.
        /// </summary>
        /// <value>URL to redirect the customer to after the payment process is completed.</value>
        /// <example>https://example.com/success</example>
        [DataMember(Name = "success_url", EmitDefaultValue = false)]
        public string SuccessUrl { get; set; }

        /// <summary>
        /// Type of checkout.
        /// </summary>
        /// <value>Type of checkout.</value>
        /// <example>Integration</example>
        [DataMember(Name = "type", EmitDefaultValue = false)]
        public string Type { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TokenResponseCheckout {\n");
            sb.Append("  AllowedPaymentMethods: ").Append(AllowedPaymentMethods).Append("\n");
            sb.Append("  CanNotExpire: ").Append(CanNotExpire).Append("\n");
            sb.Append("  EmailsSent: ").Append(EmailsSent).Append("\n");
            sb.Append("  ExcludeCardNetworks: ").Append(ExcludeCardNetworks).Append("\n");
            sb.Append("  ExpiresAt: ").Append(ExpiresAt).Append("\n");
            sb.Append("  FailureUrl: ").Append(FailureUrl).Append("\n");
            sb.Append("  Force3dsFlow: ").Append(Force3dsFlow).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Livemode: ").Append(Livemode).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("  MonthlyInstallmentsEnabled: ").Append(MonthlyInstallmentsEnabled).Append("\n");
            sb.Append("  MonthlyInstallmentsOptions: ").Append(MonthlyInstallmentsOptions).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  NeedsShippingContact: ").Append(NeedsShippingContact).Append("\n");
            sb.Append("  VarObject: ").Append(VarObject).Append("\n");
            sb.Append("  OnDemandEnabled: ").Append(OnDemandEnabled).Append("\n");
            sb.Append("  PaidPaymentsCount: ").Append(PaidPaymentsCount).Append("\n");
            sb.Append("  Recurrent: ").Append(Recurrent).Append("\n");
            sb.Append("  SmsSent: ").Append(SmsSent).Append("\n");
            sb.Append("  StartsAt: ").Append(StartsAt).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  SuccessUrl: ").Append(SuccessUrl).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TokenResponseCheckout);
        }

        /// <summary>
        /// Returns true if TokenResponseCheckout instances are equal
        /// </summary>
        /// <param name="input">Instance of TokenResponseCheckout to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TokenResponseCheckout input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.AllowedPaymentMethods == input.AllowedPaymentMethods ||
                    this.AllowedPaymentMethods != null &&
                    input.AllowedPaymentMethods != null &&
                    this.AllowedPaymentMethods.SequenceEqual(input.AllowedPaymentMethods)
                ) && 
                (
                    this.CanNotExpire == input.CanNotExpire ||
                    this.CanNotExpire.Equals(input.CanNotExpire)
                ) && 
                (
                    this.EmailsSent == input.EmailsSent ||
                    this.EmailsSent.Equals(input.EmailsSent)
                ) && 
                (
                    this.ExcludeCardNetworks == input.ExcludeCardNetworks ||
                    this.ExcludeCardNetworks != null &&
                    input.ExcludeCardNetworks != null &&
                    this.ExcludeCardNetworks.SequenceEqual(input.ExcludeCardNetworks)
                ) && 
                (
                    this.ExpiresAt == input.ExpiresAt ||
                    this.ExpiresAt.Equals(input.ExpiresAt)
                ) && 
                (
                    this.FailureUrl == input.FailureUrl ||
                    (this.FailureUrl != null &&
                    this.FailureUrl.Equals(input.FailureUrl))
                ) && 
                (
                    this.Force3dsFlow == input.Force3dsFlow ||
                    this.Force3dsFlow.Equals(input.Force3dsFlow)
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Livemode == input.Livemode ||
                    this.Livemode.Equals(input.Livemode)
                ) && 
                (
                    this.Metadata == input.Metadata ||
                    this.Metadata != null &&
                    input.Metadata != null &&
                    this.Metadata.SequenceEqual(input.Metadata)
                ) && 
                (
                    this.MonthlyInstallmentsEnabled == input.MonthlyInstallmentsEnabled ||
                    this.MonthlyInstallmentsEnabled.Equals(input.MonthlyInstallmentsEnabled)
                ) && 
                (
                    this.MonthlyInstallmentsOptions == input.MonthlyInstallmentsOptions ||
                    this.MonthlyInstallmentsOptions != null &&
                    input.MonthlyInstallmentsOptions != null &&
                    this.MonthlyInstallmentsOptions.SequenceEqual(input.MonthlyInstallmentsOptions)
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.NeedsShippingContact == input.NeedsShippingContact ||
                    this.NeedsShippingContact.Equals(input.NeedsShippingContact)
                ) && 
                (
                    this.VarObject == input.VarObject ||
                    (this.VarObject != null &&
                    this.VarObject.Equals(input.VarObject))
                ) && 
                (
                    this.OnDemandEnabled == input.OnDemandEnabled ||
                    this.OnDemandEnabled.Equals(input.OnDemandEnabled)
                ) && 
                (
                    this.PaidPaymentsCount == input.PaidPaymentsCount ||
                    this.PaidPaymentsCount.Equals(input.PaidPaymentsCount)
                ) && 
                (
                    this.Recurrent == input.Recurrent ||
                    this.Recurrent.Equals(input.Recurrent)
                ) && 
                (
                    this.SmsSent == input.SmsSent ||
                    this.SmsSent.Equals(input.SmsSent)
                ) && 
                (
                    this.StartsAt == input.StartsAt ||
                    this.StartsAt.Equals(input.StartsAt)
                ) && 
                (
                    this.Status == input.Status ||
                    (this.Status != null &&
                    this.Status.Equals(input.Status))
                ) && 
                (
                    this.SuccessUrl == input.SuccessUrl ||
                    (this.SuccessUrl != null &&
                    this.SuccessUrl.Equals(input.SuccessUrl))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AllowedPaymentMethods != null)
                {
                    hashCode = (hashCode * 59) + this.AllowedPaymentMethods.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.CanNotExpire.GetHashCode();
                hashCode = (hashCode * 59) + this.EmailsSent.GetHashCode();
                if (this.ExcludeCardNetworks != null)
                {
                    hashCode = (hashCode * 59) + this.ExcludeCardNetworks.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.ExpiresAt.GetHashCode();
                if (this.FailureUrl != null)
                {
                    hashCode = (hashCode * 59) + this.FailureUrl.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Force3dsFlow.GetHashCode();
                if (this.Id != null)
                {
                    hashCode = (hashCode * 59) + this.Id.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Livemode.GetHashCode();
                if (this.Metadata != null)
                {
                    hashCode = (hashCode * 59) + this.Metadata.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.MonthlyInstallmentsEnabled.GetHashCode();
                if (this.MonthlyInstallmentsOptions != null)
                {
                    hashCode = (hashCode * 59) + this.MonthlyInstallmentsOptions.GetHashCode();
                }
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.NeedsShippingContact.GetHashCode();
                if (this.VarObject != null)
                {
                    hashCode = (hashCode * 59) + this.VarObject.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.OnDemandEnabled.GetHashCode();
                hashCode = (hashCode * 59) + this.PaidPaymentsCount.GetHashCode();
                hashCode = (hashCode * 59) + this.Recurrent.GetHashCode();
                hashCode = (hashCode * 59) + this.SmsSent.GetHashCode();
                hashCode = (hashCode * 59) + this.StartsAt.GetHashCode();
                if (this.Status != null)
                {
                    hashCode = (hashCode * 59) + this.Status.GetHashCode();
                }
                if (this.SuccessUrl != null)
                {
                    hashCode = (hashCode * 59) + this.SuccessUrl.GetHashCode();
                }
                if (this.Type != null)
                {
                    hashCode = (hashCode * 59) + this.Type.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
