services:
  mockserver:
    restart: always
    image: mockoon/cli:2.4.0
    command: "-d data  -p 3000 --log-transaction"
    environment:
      d: data
    volumes:
      - ./mocks/conekta_api.json:/data:ro
    healthcheck:
      test: "wget -qO - http://mockserver:3000/ping"
      interval: 5s
      timeout: 10s
      retries: 20
  service:
   build:
     context: .
     dockerfile: Dockerfile
   environment:
     BASE_PATH: "http://mockserver:3000"
   depends_on:
    mockserver:
      condition: service_healthy
