/*
 * Conekta API
 *
 * Conekta sdk
 *
 * The version of the OpenAPI document: 2.2.0
 * Contact: engineering@conekta.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Conekta.net.Client;
using Conekta.net.Api;
// uncomment below to import models
//using Conekta.net.Model;

namespace Conekta.net.Test.Api
{
    /// <summary>
    ///  Class for testing TaxesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TaxesApiTests : IDisposable
    {
        private TaxesApi instance;

        public TaxesApiTests()
        {
            instance = new TaxesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TaxesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TaxesApi
            //Assert.IsType<TaxesApi>(instance);
        }

        /// <summary>
        /// Test OrdersCreateTaxes
        /// </summary>
        [Fact]
        public void OrdersCreateTaxesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //OrderTaxRequest orderTaxRequest = null;
            //string acceptLanguage = null;
            //string xChildCompanyId = null;
            //var response = instance.OrdersCreateTaxes(id, orderTaxRequest, acceptLanguage, xChildCompanyId);
            //Assert.IsType<UpdateOrderTaxResponse>(response);
        }

        /// <summary>
        /// Test OrdersDeleteTaxes
        /// </summary>
        [Fact]
        public void OrdersDeleteTaxesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string taxId = null;
            //string acceptLanguage = null;
            //string xChildCompanyId = null;
            //var response = instance.OrdersDeleteTaxes(id, taxId, acceptLanguage, xChildCompanyId);
            //Assert.IsType<UpdateOrderTaxResponse>(response);
        }

        /// <summary>
        /// Test OrdersUpdateTaxes
        /// </summary>
        [Fact]
        public void OrdersUpdateTaxesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //string taxId = null;
            //UpdateOrderTaxRequest updateOrderTaxRequest = null;
            //string acceptLanguage = null;
            //string xChildCompanyId = null;
            //var response = instance.OrdersUpdateTaxes(id, taxId, updateOrderTaxRequest, acceptLanguage, xChildCompanyId);
            //Assert.IsType<UpdateOrderTaxResponse>(response);
        }
    }
}
