name: dotnet CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x', '8.0.x']
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Run Mockoon CLI
        uses: mockoon/cli-action@v3
        with:
          data-file: 'https://raw.githubusercontent.com/conekta/openapi/main/mocks/conekta_api.json'
          port: 3000
      - name: Execute dotnet
        run: dotnet build
      - name: Run tests
        env:
          BASE_PATH: http://localhost:3000
        run: dotnet test ./src/Conekta.net.Test/Conekta.net.Test.csproj --no-build
